### ISSUE TITLE
TODO Electronic circuit

### ISSUE THREAD

**Issue by orlin369** [OpenMOBot/OpenMOBot#19]
Create electronic schematic similar to this one: https://i0.wp.com/srituhobby.com/wp-content/uploads/2021/05/circuitt2.jpg?resize=1024%2C1024&ssl=1

1. For controller use Arduino UNO.
2. For line sensor use QTR-8 the center 6 sensor in the array.
3. For motor use the same from schematic.
4. For motor driver use L298D
5. Separate the power supply to 2 pack of 4 AA batteries - one pack for the motor driver, one pack for the Arduino board.
6. Use double contact power switch to turn ON and OFF at the same time Arduino board and motor controller.

For any missing information please contact me at the working group chat.

Regards Orlin

**Comment by MeNameIsMe** [comment]
В моят Fritzing го няма този драйвър. Ще пробвам да изтегля по-нова версия. Или ще потърся откъде да изтегля драйвъра. Би трябвало да има да го добавя от техния сайт или от някой форум.
